/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package umleditor;

import java.util.ArrayList;
import javax.swing.DefaultComboBoxModel;
import javax.swing.text.Document;

/**
 *
 * @author Sean
 */
public class EditPane extends javax.swing.JPanel {

    /**
     * Creates new form EditPane
     */
    public EditPane() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        buttonGroup3 = new javax.swing.ButtonGroup();
        tabbedPanel = new javax.swing.JTabbedPane();
        classesPanel = new javax.swing.JPanel();
        classesSelectedClassCB = new javax.swing.JComboBox<>();
        classesSelectedClassLB = new javax.swing.JLabel();
        classNameLB = new javax.swing.JLabel();
        classNameTF = new javax.swing.JTextField();
        classTypeLB = new javax.swing.JLabel();
        classTypeCB = new javax.swing.JComboBox<>();
        classesApplyBT = new javax.swing.JButton();
        classesDeleteBT = new javax.swing.JButton();
        classesResetBT = new javax.swing.JButton();
        associationsPanel = new javax.swing.JPanel();
        selectedClassALB = new javax.swing.JLabel();
        selectedClassACB = new javax.swing.JComboBox<>();
        selectedClassBLB = new javax.swing.JLabel();
        selectedClassBCB = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        associationTypeCB = new javax.swing.JComboBox<>();
        associactionDirectionLB = new javax.swing.JLabel();
        aToBRB = new javax.swing.JRadioButton();
        bToARB = new javax.swing.JRadioButton();
        associationLabelLB = new javax.swing.JLabel();
        associationLabelTF = new javax.swing.JTextField();
        multiplicitiesPanel = new javax.swing.JPanel();
        multiplicitiesLB = new javax.swing.JLabel();
        aSideMultiplicitiesLB = new javax.swing.JLabel();
        aSideMultiplicitiesTF = new javax.swing.JTextField();
        bSideMultiplicitiesTF = new javax.swing.JTextField();
        bSideMultiplicitiesLB = new javax.swing.JLabel();
        associationsApplyBT = new javax.swing.JButton();
        associationsDeleteBT = new javax.swing.JButton();
        associationsResetBT = new javax.swing.JButton();
        mnfPanel = new javax.swing.JPanel();
        mnfSelectedClassLB = new javax.swing.JLabel();
        mnfSelectedClassCB = new javax.swing.JComboBox<>();
        selectedAttributeLB = new javax.swing.JLabel();
        selectedAttributeCB = new javax.swing.JComboBox<>();
        attributeNameLB = new javax.swing.JLabel();
        attributeNameTF = new javax.swing.JTextField();
        methodsRB = new javax.swing.JRadioButton();
        fieldsRB = new javax.swing.JRadioButton();
        visibilityLB = new javax.swing.JLabel();
        visibilityCB = new javax.swing.JComboBox<>();
        staticCheckBox = new javax.swing.JCheckBox();
        abstractCheckBox = new javax.swing.JCheckBox();
        mnfApplyBT = new javax.swing.JButton();
        mnfDeleteBT = new javax.swing.JButton();
        mnfResetBT = new javax.swing.JButton();
        sourcePanel = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        sourceTextArea = new javax.swing.JTextArea();
        sourceApplyBT = new javax.swing.JButton();
        sourceResetBT = new javax.swing.JButton();

        tabbedPanel.setToolTipText("");
        tabbedPanel.setName(""); // NOI18N

        classesSelectedClassCB.setMaximumRowCount(99999);
        classesSelectedClassCB.setModel(new DefaultComboBoxModel(UMLUtilities.classNames(sourceTextArea.getText()).toArray()));
        classesSelectedClassCB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                classesSelectedClassCBActionPerformed(evt);
            }
        });

        classesSelectedClassLB.setText("Selected Class");

        classNameLB.setText("Class Name");

        classTypeLB.setText("Class Type");

        classTypeCB.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Concrete", "Abstract" }));
        classTypeCB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                classTypeCBActionPerformed(evt);
            }
        });

        classesApplyBT.setText("Apply");
        classesApplyBT.setMaximumSize(new java.awt.Dimension(64, 25));
        classesApplyBT.setMinimumSize(new java.awt.Dimension(64, 25));
        classesApplyBT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                classesApplyBTActionPerformed(evt);
            }
        });

        classesDeleteBT.setText("Delete");
        classesDeleteBT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                classesDeleteBTActionPerformed(evt);
            }
        });

        classesResetBT.setText("Reset");
        classesResetBT.setMaximumSize(new java.awt.Dimension(64, 25));
        classesResetBT.setMinimumSize(new java.awt.Dimension(64, 25));
        classesResetBT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                classesResetBTActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout classesPanelLayout = new javax.swing.GroupLayout(classesPanel);
        classesPanel.setLayout(classesPanelLayout);
        classesPanelLayout.setHorizontalGroup(
            classesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(classesPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(classesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(classesSelectedClassCB, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(classNameTF)
                    .addComponent(classTypeCB, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(classesPanelLayout.createSequentialGroup()
                        .addGroup(classesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(classesSelectedClassLB)
                            .addComponent(classNameLB)
                            .addComponent(classTypeLB))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, classesPanelLayout.createSequentialGroup()
                        .addComponent(classesApplyBT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 71, Short.MAX_VALUE)
                        .addComponent(classesDeleteBT)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 71, Short.MAX_VALUE)
                        .addComponent(classesResetBT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        classesPanelLayout.setVerticalGroup(
            classesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(classesPanelLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(classesSelectedClassLB)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(classesSelectedClassCB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(classNameLB)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(classNameTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(classTypeLB)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(classTypeCB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 185, Short.MAX_VALUE)
                .addGroup(classesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(classesApplyBT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(classesDeleteBT)
                    .addComponent(classesResetBT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        tabbedPanel.addTab("Classes", classesPanel);

        selectedClassALB.setText("Selected Class A");

        selectedClassACB.setMaximumRowCount(99999);
        selectedClassACB.setModel(new DefaultComboBoxModel(UMLUtilities.classNames(sourceTextArea.getText()).toArray()));
        selectedClassACB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                selectedClassACBActionPerformed(evt);
            }
        });

        selectedClassBLB.setText("Selected Class B");

        selectedClassBCB.setMaximumRowCount(999999);
        selectedClassBCB.setModel(new DefaultComboBoxModel(UMLUtilities.classNames(sourceTextArea.getText()).toArray()));

        jLabel6.setText("Association");

        associationTypeCB.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Extension", "Composition", "Aggregation", "Ordinary" }));

        associactionDirectionLB.setText("Direction");

        buttonGroup1.add(aToBRB);
        aToBRB.setSelected(true);
        aToBRB.setText("AtoB");

        buttonGroup1.add(bToARB);
        bToARB.setText("BtoA");
        bToARB.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                bToARBStateChanged(evt);
            }
        });

        associationLabelLB.setText("Association Label");

        multiplicitiesLB.setText("Multiplicities");

        aSideMultiplicitiesLB.setText("A-Side");

        aSideMultiplicitiesTF.setMaximumSize(new java.awt.Dimension(55, 19));
        aSideMultiplicitiesTF.setMinimumSize(new java.awt.Dimension(55, 19));
        aSideMultiplicitiesTF.setName(""); // NOI18N
        aSideMultiplicitiesTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aSideMultiplicitiesTFActionPerformed(evt);
            }
        });

        bSideMultiplicitiesTF.setMaximumSize(new java.awt.Dimension(55, 19));
        bSideMultiplicitiesTF.setMinimumSize(new java.awt.Dimension(55, 19));

        bSideMultiplicitiesLB.setText("B-Side");

        javax.swing.GroupLayout multiplicitiesPanelLayout = new javax.swing.GroupLayout(multiplicitiesPanel);
        multiplicitiesPanel.setLayout(multiplicitiesPanelLayout);
        multiplicitiesPanelLayout.setHorizontalGroup(
            multiplicitiesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, multiplicitiesPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(multiplicitiesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(aSideMultiplicitiesTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(multiplicitiesPanelLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(aSideMultiplicitiesLB)))
                .addGap(24, 24, 24)
                .addGroup(multiplicitiesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, multiplicitiesPanelLayout.createSequentialGroup()
                        .addComponent(bSideMultiplicitiesTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, multiplicitiesPanelLayout.createSequentialGroup()
                        .addComponent(bSideMultiplicitiesLB)
                        .addGap(23, 23, 23))))
            .addGroup(multiplicitiesPanelLayout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(multiplicitiesLB)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        multiplicitiesPanelLayout.setVerticalGroup(
            multiplicitiesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(multiplicitiesPanelLayout.createSequentialGroup()
                .addComponent(multiplicitiesLB)
                .addGap(21, 21, 21)
                .addGroup(multiplicitiesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(aSideMultiplicitiesLB, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(bSideMultiplicitiesLB))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(multiplicitiesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bSideMultiplicitiesTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(aSideMultiplicitiesTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        associationsApplyBT.setText("Apply");
        associationsApplyBT.setMaximumSize(new java.awt.Dimension(64, 25));
        associationsApplyBT.setMinimumSize(new java.awt.Dimension(64, 25));
        associationsApplyBT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                associationsApplyBTActionPerformed(evt);
            }
        });

        associationsDeleteBT.setText("Delete");
        associationsDeleteBT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                associationsDeleteBTActionPerformed(evt);
            }
        });

        associationsResetBT.setText("Reset");
        associationsResetBT.setMaximumSize(new java.awt.Dimension(64, 25));
        associationsResetBT.setMinimumSize(new java.awt.Dimension(64, 25));
        associationsResetBT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                associationsResetBTActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout associationsPanelLayout = new javax.swing.GroupLayout(associationsPanel);
        associationsPanel.setLayout(associationsPanelLayout);
        associationsPanelLayout.setHorizontalGroup(
            associationsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(associationsPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(associationsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(associationsPanelLayout.createSequentialGroup()
                        .addComponent(associationLabelLB)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(multiplicitiesPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(57, 57, 57))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, associationsPanelLayout.createSequentialGroup()
                        .addGroup(associationsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(associationsPanelLayout.createSequentialGroup()
                                .addComponent(associationsApplyBT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 71, Short.MAX_VALUE)
                                .addComponent(associationsDeleteBT)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 71, Short.MAX_VALUE)
                                .addComponent(associationsResetBT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(selectedClassACB, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(selectedClassBCB, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(associationTypeCB, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(associationLabelTF, javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, associationsPanelLayout.createSequentialGroup()
                                .addGroup(associationsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(associactionDirectionLB, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(aToBRB, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(bToARB, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(selectedClassALB, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(selectedClassBLB, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.LEADING))
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addContainerGap())))
        );
        associationsPanelLayout.setVerticalGroup(
            associationsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(associationsPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(selectedClassALB)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(selectedClassACB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(selectedClassBLB)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(selectedClassBCB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(associationTypeCB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(associationsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(associationsPanelLayout.createSequentialGroup()
                        .addComponent(associactionDirectionLB)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(aToBRB)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(bToARB)
                        .addGap(18, 18, 18)
                        .addComponent(associationLabelLB))
                    .addComponent(multiplicitiesPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(associationLabelTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 38, Short.MAX_VALUE)
                .addGroup(associationsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(associationsApplyBT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(associationsDeleteBT)
                    .addComponent(associationsResetBT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        tabbedPanel.addTab("Associations", associationsPanel);

        mnfSelectedClassLB.setText("Selected Class");

        mnfSelectedClassCB.setMaximumRowCount(99999);
        mnfSelectedClassCB.setModel(new DefaultComboBoxModel(UMLUtilities.classNames(sourceTextArea.getText()).toArray()));

        selectedAttributeLB.setText("Selected Attribute");

        selectedAttributeCB.setMaximumRowCount(99999);
        selectedAttributeCB.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        selectedAttributeCB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                selectedAttributeCBActionPerformed(evt);
            }
        });

        attributeNameLB.setText("Attribute Name");

        buttonGroup2.add(methodsRB);
        methodsRB.setSelected(true);
        methodsRB.setText("Methods");
        methodsRB.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                methodsRBItemStateChanged(evt);
            }
        });
        methodsRB.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                methodsRBStateChanged(evt);
            }
        });
        methodsRB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                methodsRBActionPerformed(evt);
                methodsRBActionPerformed1(evt);
            }
        });

        buttonGroup2.add(fieldsRB);
        fieldsRB.setText("Fields");
        fieldsRB.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                fieldsRBStateChanged(evt);
            }
        });
        fieldsRB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fieldsRBActionPerformed(evt);
                fieldsRBActionPerformed1(evt);
            }
        });

        visibilityLB.setText("Visibility");

        visibilityCB.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Private", "Protected", "Package Private", "Public" }));

        staticCheckBox.setText("Static");
        staticCheckBox.setToolTipText("");

        abstractCheckBox.setText("Abstract");

        mnfApplyBT.setText("Apply");
        mnfApplyBT.setMaximumSize(new java.awt.Dimension(64, 25));
        mnfApplyBT.setMinimumSize(new java.awt.Dimension(64, 25));
        mnfApplyBT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnfApplyBTActionPerformed(evt);
            }
        });

        mnfDeleteBT.setText("Delete");
        mnfDeleteBT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnfDeleteBTActionPerformed(evt);
            }
        });

        mnfResetBT.setText("Reset");
        mnfResetBT.setMaximumSize(new java.awt.Dimension(64, 25));
        mnfResetBT.setMinimumSize(new java.awt.Dimension(64, 25));
        mnfResetBT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnfResetBTActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout mnfPanelLayout = new javax.swing.GroupLayout(mnfPanel);
        mnfPanel.setLayout(mnfPanelLayout);
        mnfPanelLayout.setHorizontalGroup(
            mnfPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mnfPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(mnfPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(mnfSelectedClassCB, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(selectedAttributeCB, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(attributeNameTF)
                    .addComponent(visibilityCB, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(mnfPanelLayout.createSequentialGroup()
                        .addGroup(mnfPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(mnfSelectedClassLB)
                            .addComponent(selectedAttributeLB)
                            .addComponent(attributeNameLB)
                            .addComponent(methodsRB)
                            .addComponent(visibilityLB)
                            .addComponent(staticCheckBox)
                            .addComponent(abstractCheckBox)
                            .addComponent(fieldsRB))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(mnfPanelLayout.createSequentialGroup()
                        .addComponent(mnfApplyBT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 70, Short.MAX_VALUE)
                        .addComponent(mnfDeleteBT)
                        .addGap(72, 72, 72)
                        .addComponent(mnfResetBT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        mnfPanelLayout.setVerticalGroup(
            mnfPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mnfPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(mnfSelectedClassLB)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(mnfSelectedClassCB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(methodsRB)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(fieldsRB)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(selectedAttributeLB)
                .addGap(3, 3, 3)
                .addComponent(selectedAttributeCB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(attributeNameLB)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(attributeNameTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(visibilityLB)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(visibilityCB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(staticCheckBox)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(abstractCheckBox)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(mnfPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(mnfApplyBT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(mnfDeleteBT)
                    .addComponent(mnfResetBT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        tabbedPanel.addTab("Methods & Fields", mnfPanel);

        sourceTextArea.setColumns(20);
        sourceTextArea.setRows(5);
        sourceTextArea.setText("@startuml\n\n@enduml");
        jScrollPane1.setViewportView(sourceTextArea);

        sourceApplyBT.setText("Apply");
        sourceApplyBT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sourceApplyBTActionPerformed(evt);
            }
        });

        sourceResetBT.setText("Reset");
        sourceResetBT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sourceResetBTActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout sourcePanelLayout = new javax.swing.GroupLayout(sourcePanel);
        sourcePanel.setLayout(sourcePanelLayout);
        sourcePanelLayout.setHorizontalGroup(
            sourcePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sourcePanelLayout.createSequentialGroup()
                .addGroup(sourcePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(sourcePanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1))
                    .addGroup(sourcePanelLayout.createSequentialGroup()
                        .addContainerGap(88, Short.MAX_VALUE)
                        .addComponent(sourceApplyBT)
                        .addGap(42, 42, 42)
                        .addComponent(sourceResetBT)
                        .addGap(0, 88, Short.MAX_VALUE)))
                .addContainerGap())
        );
        sourcePanelLayout.setVerticalGroup(
            sourcePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sourcePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 327, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                .addGroup(sourcePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(sourceApplyBT)
                    .addComponent(sourceResetBT))
                .addContainerGap())
        );

        tabbedPanel.addTab("Source", sourcePanel);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tabbedPanel, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(tabbedPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 429, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void classTypeCBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_classTypeCBActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_classTypeCBActionPerformed

    private void selectedAttributeCBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_selectedAttributeCBActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_selectedAttributeCBActionPerformed

    private void fieldsRBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fieldsRBActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fieldsRBActionPerformed

    private void mnfApplyBTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnfApplyBTActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mnfApplyBTActionPerformed

    private void mnfDeleteBTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnfDeleteBTActionPerformed
    	if (methodsRB.getAutoscrolls())
    		sourceTextArea.setText(UMLUtilities.deleteMethod(sourceTextArea.getText(), (String)mnfSelectedClassCB.getSelectedItem(), attributeNameTF.getText()));
    	else
    		sourceTextArea.setText(UMLUtilities.deleteField(sourceTextArea.getText(), (String)mnfSelectedClassCB.getSelectedItem(), attributeNameTF.getText()));
    	loaded();
    }//GEN-LAST:event_mnfDeleteBTActionPerformed

    private void sourceApplyBTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sourceApplyBTActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_sourceApplyBTActionPerformed

    private void associationsApplyBTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_associationsApplyBTActionPerformed
        String classA = (String)selectedClassACB.getSelectedItem();
        String classB = (String)selectedClassBCB.getSelectedItem();
        String source = sourceTextArea.getText();
        String assTypeString = (String)associationTypeCB.getSelectedItem();
        char assType = 0;
        if (assTypeString.equals("Extension"))
        	assType = '|';
        else if (assTypeString.equals("Composition"))
        	assType = '*';
        else if (assTypeString.equals("Aggregation"))
        	assType = 'o';
        else // (assTypeString.equals("Ordinary"))
        	assType = '-';
        boolean aToB = aToBRB.isSelected();
        String label = associationLabelTF.getText();
        if (!UMLUtilities.assAtoB(source, classA, classB) && !UMLUtilities.assAtoB(source, classB, classA))
        	UMLUtilities.createAss(source, classA, classB, assType, aToB, label);
    }//GEN-LAST:event_associationsApplyBTActionPerformed

    private void associationsDeleteBTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_associationsDeleteBTActionPerformed
    	sourceTextArea.setText(UMLUtilities.removeAss(sourceTextArea.getText(), (String)selectedClassACB.getSelectedItem(), (String)selectedClassBCB.getSelectedItem()));
    	loaded();
    }//GEN-LAST:event_associationsDeleteBTActionPerformed

    private void classesApplyBTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_classesApplyBTActionPerformed
        String className = classNameTF.getText();
        className.replaceAll(" ", "");
        if (classesSelectedClassCB.getSelectedItem().equals("new class"))
        	sourceTextArea.setText(UMLUtilities.createClass(sourceTextArea.getText(), className));
        else {
        	sourceTextArea.setText(UMLUtilities.renameClass(sourceTextArea.getText(), (String)classesSelectedClassCB.getSelectedItem(), classNameTF.getText()));
        	boolean isAbstract = true;
        	if (classTypeCB.getSelectedItem().equals("Concrete"))
        		isAbstract = false;
        	sourceTextArea.setText(UMLUtilities.setClassIsAbstract(sourceTextArea.getText(), className, isAbstract));
                
        }
    }//GEN-LAST:event_classesApplyBTActionPerformed

    private void classesDeleteBTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_classesDeleteBTActionPerformed
    	sourceTextArea.setText(UMLUtilities.deleteClass(sourceTextArea.getText(), (String)classesSelectedClassCB.getSelectedItem()));
    	loaded();
    }//GEN-LAST:event_classesDeleteBTActionPerformed

    private void bToARBStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_bToARBStateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_bToARBStateChanged

    private void selectedClassACBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_selectedClassACBActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_selectedClassACBActionPerformed

    private void aSideMultiplicitiesTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aSideMultiplicitiesTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_aSideMultiplicitiesTFActionPerformed

    private void methodsRBStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_methodsRBStateChanged
        fieldsRB.setSelected(false);
    }//GEN-LAST:event_methodsRBStateChanged

    private void fieldsRBStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_fieldsRBStateChanged
        methodsRB.setSelected(false);
    }//GEN-LAST:event_fieldsRBStateChanged

    private void methodsRBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_methodsRBActionPerformed
        fieldsRB.setSelected(false);
    }//GEN-LAST:event_methodsRBActionPerformed

    private void methodsRBActionPerformed1(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_methodsRBActionPerformed1
        fieldsRB.setSelected(false);
    }//GEN-LAST:event_methodsRBActionPerformed1

    private void fieldsRBActionPerformed1(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fieldsRBActionPerformed1
        methodsRB.setSelected(false);
    }//GEN-LAST:event_fieldsRBActionPerformed1

    private void methodsRBItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_methodsRBItemStateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_methodsRBItemStateChanged

    private void classesSelectedClassCBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_classesSelectedClassCBActionPerformed
        classNameTF.setText((String)classesSelectedClassCB.getSelectedItem());
        if(UMLUtilities.classIsAbstract(getSourceText(), classNameTF.getText())) {
            classTypeCB.setSelectedIndex(1);
        }
        else {
            classTypeCB.setSelectedIndex(0);
        }
    }//GEN-LAST:event_classesSelectedClassCBActionPerformed

    private void classesResetBTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_classesResetBTActionPerformed
        loaded();
    }//GEN-LAST:event_classesResetBTActionPerformed

    private void associationsResetBTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_associationsResetBTActionPerformed
        loaded();
    }//GEN-LAST:event_associationsResetBTActionPerformed

    private void mnfResetBTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnfResetBTActionPerformed
        loaded();
    }//GEN-LAST:event_mnfResetBTActionPerformed

    private void sourceResetBTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sourceResetBTActionPerformed
        sourceTextArea.setText(originalText);
    }//GEN-LAST:event_sourceResetBTActionPerformed

    private String originalText;
    
    public void setFieldDocument(Document doc) {
        sourceTextArea.setDocument(doc);
        originalText = sourceTextArea.getText();
    }
    
    /**
     * run once the document has been loaded via UMLDocument
     */
    public void loaded() {
        updateClassesSelectedClassCB();
        updateSelectedClassACB();
        updateSelectedClassBCB();
        updateMnfSelectedClassCB();
    }
    
    public String getSourceText() {
        return sourceTextArea.getText();
    }
    
    private void updateClassesSelectedClassCB() {
        classesSelectedClassCB.removeAllItems();
        classesSelectedClassCB.addItem("new class");
        ArrayList<String> classes = UMLUtilities.classNames(sourceTextArea.getText());
        for(String className : classes) {
            classesSelectedClassCB.addItem(className);
        }
    }
    
    private void updateSelectedClassACB() {
        selectedClassACB.removeAllItems();
        ArrayList<String> classes = UMLUtilities.classNames(sourceTextArea.getText());
        for(String className : classes) {
            selectedClassACB.addItem(className);
        }
    }
    
    private void updateSelectedClassBCB() {
        selectedClassBCB.removeAllItems();
        ArrayList<String> classes = UMLUtilities.classNames(sourceTextArea.getText());
        for(String className : classes) {
            selectedClassBCB.addItem(className);
        }
    }
    
    private void updateMnfSelectedClassCB() {
        mnfSelectedClassCB.removeAllItems();
        ArrayList<String> classes = UMLUtilities.classNames(sourceTextArea.getText());
        for(String className : classes) {
            mnfSelectedClassCB.addItem(className);
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel aSideMultiplicitiesLB;
    private javax.swing.JTextField aSideMultiplicitiesTF;
    private javax.swing.JRadioButton aToBRB;
    private javax.swing.JCheckBox abstractCheckBox;
    private javax.swing.JLabel associactionDirectionLB;
    private javax.swing.JLabel associationLabelLB;
    private javax.swing.JTextField associationLabelTF;
    private javax.swing.JComboBox<String> associationTypeCB;
    private javax.swing.JButton associationsApplyBT;
    private javax.swing.JButton associationsDeleteBT;
    private javax.swing.JPanel associationsPanel;
    private javax.swing.JButton associationsResetBT;
    private javax.swing.JLabel attributeNameLB;
    private javax.swing.JTextField attributeNameTF;
    private javax.swing.JLabel bSideMultiplicitiesLB;
    private javax.swing.JTextField bSideMultiplicitiesTF;
    private javax.swing.JRadioButton bToARB;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.JLabel classNameLB;
    private javax.swing.JTextField classNameTF;
    private javax.swing.JComboBox<String> classTypeCB;
    private javax.swing.JLabel classTypeLB;
    private javax.swing.JButton classesApplyBT;
    private javax.swing.JButton classesDeleteBT;
    private javax.swing.JPanel classesPanel;
    private javax.swing.JButton classesResetBT;
    private javax.swing.JComboBox<String> classesSelectedClassCB;
    private javax.swing.JLabel classesSelectedClassLB;
    private javax.swing.JRadioButton fieldsRB;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JRadioButton methodsRB;
    private javax.swing.JButton mnfApplyBT;
    private javax.swing.JButton mnfDeleteBT;
    private javax.swing.JPanel mnfPanel;
    private javax.swing.JButton mnfResetBT;
    private javax.swing.JComboBox<String> mnfSelectedClassCB;
    private javax.swing.JLabel mnfSelectedClassLB;
    private javax.swing.JLabel multiplicitiesLB;
    private javax.swing.JPanel multiplicitiesPanel;
    private javax.swing.JComboBox<String> selectedAttributeCB;
    private javax.swing.JLabel selectedAttributeLB;
    private javax.swing.JComboBox<String> selectedClassACB;
    private javax.swing.JLabel selectedClassALB;
    private javax.swing.JComboBox<String> selectedClassBCB;
    private javax.swing.JLabel selectedClassBLB;
    private javax.swing.JButton sourceApplyBT;
    private javax.swing.JPanel sourcePanel;
    private javax.swing.JButton sourceResetBT;
    private javax.swing.JTextArea sourceTextArea;
    private javax.swing.JCheckBox staticCheckBox;
    private javax.swing.JTabbedPane tabbedPanel;
    private javax.swing.JComboBox<String> visibilityCB;
    private javax.swing.JLabel visibilityLB;
    // End of variables declaration//GEN-END:variables
}
